# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"build_volume_manifest": "manifest_generation.ipynb",
         "write_server": "manifest_generation.ipynb",
         "build_volume_records": "s3_scrape.ipynb",
         "scrape_bucket": "s3_scrape.ipynb",
         "ssda_volume_xml_to_dict": "s3_scrape.ipynb"}

modules = ["manifest_gen.py",
           "s3_scrape.py"]

doc_url = "https://slavesocieties.github.io/ssda-website-v2/"

git_url = "https://github.com/slavesocieties/ssda-website-v2/tree/main/"

def custom_doc_links(name): return None
